# SPDX-License-Identifier: GPL-2.0

TEST_GEN_PROGS_EXTENDED := lp_test_getpid

TEST_PROGS_EXTENDED := functions.sh
TEST_PROGS := \
	test-livepatch.sh \
	test-callbacks.sh \
	test-shadow-vars.sh \
	test-state.sh \
	test-ftrace.sh \
	test-syscall.sh \
	test-multi-fast-lps.sh

TEST_FILES := settings

include ../lib.mk
